### ISSUE TITLE
Question: Does the android app support copy/paste for RCON ?

### ISSUE THREAD

**Issue by Okesik** [daparker/checkvalve#15]
Hello there !

Found this app recently and it is pretty useful, though to manage some unwanted player behavior, I'd like to copy SteamID rather than painstakingly write it on a virtual keyboard.

Would that be possible, or perhaps, is it there somewhere and I didn't notice ?

**Comment by daparker** [comment]
Hello! Thanks for the feedback. It should be possible to make the text in the RCON console selectable, which would allow you to copy it as well. I'll try to get that implemented and include it in the next release.

**Comment by daparker** [comment]
@Okesik I just posted an update, and the text in the RCON console is now selectable as of CheckValve 2.0.13 (commit [d9356fe](https://github.com/daparker/checkvalve/commit/d9356fed8a33389d78a02a9dd1de775595d6e7c0)).  Please install this update from the Play Store when it becomes available, and report back here if the issue is not fiuxed or if you run into any issues with the update.  Thanks!

**Comment by Okesik** [comment]
Seems to be working fine on my Insurgency server, ta !
